In [15]:
import numpy as np

print("Numpy version:", np.__version__)

arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Array Shape:", arr2.shape)
print("Array Data Type:", arr1.dtype)
print("Array Sum:", np.sum(arr1))
print("Array Mean:", np.mean(arr1))
print("Array Standard Deviation:", np.std(arr1))
print("Array Max:", np.max(arr1))
print("Array Min:", np.min(arr1))

zero_array=np.zeros((3,4))
one_array=np.ones((2,5))
print("Zero Array:\n", zero_array)
print("One Array:\n", one_array)

range_array=np.arange(0,20,3)
print("Range Array:", range_array)


Numpy version: 2.3.4
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array Shape: (2, 3)
Array Data Type: int64
Array Sum: 15
Array Mean: 3.0
Array Standard Deviation: 1.4142135623730951
Array Max: 5
Array Min: 1
Zero Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Range Array: [ 0  3  6  9 12 15 18]


In [21]:
a=np.array([1,2])
b=np.array([[5,6],[7,8]])

print("Matrix Addition:\n", a+b)
print("Matrix Multiplication:\n", a*b)
print("Matrix Subtraction:\n", a-b)

print("power:\n", np.power(a,2))


Matrix Addition:
 [[ 6  8]
 [ 8 10]]
Matrix Multiplication:
 [[ 5 12]
 [ 7 16]]
Matrix Subtraction:
 [[-4 -4]
 [-6 -6]]
power:
 [1 4]
